version: '3.7'
services:
  web:
    build: .
    volumes:
      - ./:/app
       - /app/node_modules
    working_dir: /app
    ports:
      - 8080:8080
    environment:
      NODE_ENV: development
      VUE_APP_API: http://localhost:3000/api/v1